blank_issues_enabled: true
contact_links:
  - name: s&box dedicated server bugs
    url: https://github.com/Facepunch/sbox-issues/issues
    about: For issues with sbox-server.exe / sbox-server.dll itself, file with Facepunch.
